steps:
- name: ubuntu
  args: ['bash', './registry_npmjs.sh', '$_NPM_TOKEN']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'install', '--pure-lockfile']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'build']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'build:server']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'deploy:assets']
  env: ['PUBLIC_PATH=//frankassets-cdn.azureedge.net/assets/frank/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-front:$BRANCH_NAME-$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-front:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-front=gcr.io/$PROJECT_ID/frank-front:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']
