steps:
- name: ubuntu
  args: ['bash', './registry_npmjs.sh', '$_NPM_TOKEN']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'install', '--pure-lockfile']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'build']
  env: ['WEBAPP_ASSETS_PATH=$_WEBAPP_ASSETS_PATH']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'build:server']
  env: ['WEBAPP_ASSETS_PATH=$_WEBAPP_ASSETS_PATH']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'deploy']
  env: ['GOOGLE_BUCKET_NAME=$_GOOGLE_BUCKET_NAME', 'GOOGLE_BUCKET_PATH=$_GOOGLE_BUCKET_PATH', 'GOOGLE_KEYS=$_GOOGLE_KEYS', 'GOOGLE_PROJECT=$PROJECT_ID']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'build-widget']
  env: ['WIDGET_ASSETS_PATH=$_WIDGET_ASSETS_PATH']
- name: 'mhart/alpine-node:9'
  args: ['yarn', 'run', 'deploy:widget']
  env: ['GOOGLE_BUCKET_NAME=$_GOOGLE_BUCKET_NAME', 'GOOGLE_BUCKET_PATH=$_GOOGLE_BUCKET_PATH', 'GOOGLE_KEYS=$_GOOGLE_KEYS', 'GOOGLE_PROJECT=$PROJECT_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-front:$BRANCH_NAME-$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-front:$BRANCH_NAME-$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-front=gcr.io/$PROJECT_ID/frank-front:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']
