// flow-typed signature: 4c92f572a69653f3d08105f28d62769c
// flow-typed version: <<STUB>>/date-fns/fp_v2.0.0-alpha.7/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns/fp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-fns/fp' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-fns/fp/_lib/convertToFP/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addDays/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addDaysWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addHours/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addHoursWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addISOYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addISOYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addMilliseconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addMillisecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addMinutes/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addMinutesWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addMonths/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addMonthsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addQuarters/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addQuartersWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addSeconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addSecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addWeeks/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addWeeksWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/addYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/areIntervalsOverlapping/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/areIntervalsOverlappingWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/closestIndexTo/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/closestIndexToWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/closestTo/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/closestToWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/compareAsc/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/compareAscWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/compareDesc/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/compareDescWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarDays/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarDaysWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarISOWeeks/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarISOWeeksWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarISOYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarISOYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarMonths/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarMonthsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarQuarters/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarQuartersWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarWeeks/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarWeeksWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInCalendarYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInDays/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInDaysWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInHours/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInHoursWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInISOYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInISOYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInMilliseconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInMillisecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInMinutes/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInMinutesWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInMonths/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInMonthsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInQuarters/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInQuartersWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInSeconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInSecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInWeeks/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInWeeksWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/differenceInYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/eachDayOfInterval/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/eachDayOfIntervalWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfDay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfDayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfHour/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfHourWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfISOWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfISOWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfISOYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfISOYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfMinute/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfMinuteWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfQuarter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfQuarterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfSecond/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfSecondWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/endOfYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/format/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatDistance/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatDistanceStrict/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatDistanceStrictWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatDistanceWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatRelative/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatRelativeWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/formatWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDate/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDateWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDayOfYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDayOfYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDaysInMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDaysInMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDaysInYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDaysInYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getDayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getHours/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getHoursWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISODay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISODayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISOWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISOWeeksInYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISOWeeksInYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISOWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISOYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getISOYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getMilliseconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getMillisecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getMinutes/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getMinutesWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getOverlappingDaysInIntervals/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getOverlappingDaysInIntervalsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getQuarter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getQuarterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getSeconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getSecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getTime/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getTimeWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/getYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isAfter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isAfterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isBefore/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isBeforeWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isEqual/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isEqualWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isFirstDayOfMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isFirstDayOfMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isFriday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isFridayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isLastDayOfMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isLastDayOfMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isLeapYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isLeapYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isMonday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isMondayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameDay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameDayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameHour/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameHourWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameISOWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameISOWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameISOYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameISOYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameMinute/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameMinuteWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameQuarter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameQuarterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameSecond/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameSecondWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSameYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSaturday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSaturdayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSunday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isSundayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isThursday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isThursdayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isTuesday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isTuesdayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isValid/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isValidWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isWednesday/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isWednesdayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isWeekend/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isWeekendWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isWithinInterval/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/isWithinIntervalWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfISOWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfISOWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfISOYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfISOYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfQuarter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfQuarterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/lastDayOfYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/max/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/maxWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/min/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/minWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/parse/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/parseWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setDate/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setDateWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setDay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setDayOfYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setDayOfYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setDayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setHours/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setHoursWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setISODay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setISODayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setISOWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setISOWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setISOYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setISOYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setMilliseconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setMillisecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setMinutes/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setMinutesWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setQuarter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setQuarterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setSeconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setSecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/setYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfDay/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfDayWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfHour/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfHourWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfISOWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfISOWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfISOYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfISOYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfMinute/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfMinuteWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfMonth/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfMonthWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfQuarter/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfQuarterWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfSecond/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfSecondWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfWeek/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfWeekWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfYear/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/startOfYearWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subDays/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subDaysWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subHours/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subHoursWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subISOYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subISOYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subMilliseconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subMillisecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subMinutes/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subMinutesWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subMonths/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subMonthsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subQuarters/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subQuartersWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subSeconds/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subSecondsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subWeeks/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subWeeksWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subYears/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/subYearsWithOptions/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/toDate/index' {
  declare module.exports: any
}

declare module 'date-fns/fp/toDateWithOptions/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'date-fns/fp/_lib/convertToFP/index.js' {
  declare module.exports: $Exports<'date-fns/fp/_lib/convertToFP/index'>
}
declare module 'date-fns/fp/addDays/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addDays/index'>
}
declare module 'date-fns/fp/addDaysWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addDaysWithOptions/index'>
}
declare module 'date-fns/fp/addHours/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addHours/index'>
}
declare module 'date-fns/fp/addHoursWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addHoursWithOptions/index'>
}
declare module 'date-fns/fp/addISOYears/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addISOYears/index'>
}
declare module 'date-fns/fp/addISOYearsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addISOYearsWithOptions/index'>
}
declare module 'date-fns/fp/addMilliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addMilliseconds/index'>
}
declare module 'date-fns/fp/addMillisecondsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/addMillisecondsWithOptions/index'
  >
}
declare module 'date-fns/fp/addMinutes/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addMinutes/index'>
}
declare module 'date-fns/fp/addMinutesWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addMinutesWithOptions/index'>
}
declare module 'date-fns/fp/addMonths/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addMonths/index'>
}
declare module 'date-fns/fp/addMonthsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addMonthsWithOptions/index'>
}
declare module 'date-fns/fp/addQuarters/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addQuarters/index'>
}
declare module 'date-fns/fp/addQuartersWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addQuartersWithOptions/index'>
}
declare module 'date-fns/fp/addSeconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addSeconds/index'>
}
declare module 'date-fns/fp/addSecondsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addSecondsWithOptions/index'>
}
declare module 'date-fns/fp/addWeeks/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addWeeks/index'>
}
declare module 'date-fns/fp/addWeeksWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addWeeksWithOptions/index'>
}
declare module 'date-fns/fp/addYears/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addYears/index'>
}
declare module 'date-fns/fp/addYearsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/addYearsWithOptions/index'>
}
declare module 'date-fns/fp/areIntervalsOverlapping/index.js' {
  declare module.exports: $Exports<'date-fns/fp/areIntervalsOverlapping/index'>
}
declare module 'date-fns/fp/areIntervalsOverlappingWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/areIntervalsOverlappingWithOptions/index'
  >
}
declare module 'date-fns/fp/closestIndexTo/index.js' {
  declare module.exports: $Exports<'date-fns/fp/closestIndexTo/index'>
}
declare module 'date-fns/fp/closestIndexToWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/closestIndexToWithOptions/index'
  >
}
declare module 'date-fns/fp/closestTo/index.js' {
  declare module.exports: $Exports<'date-fns/fp/closestTo/index'>
}
declare module 'date-fns/fp/closestToWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/closestToWithOptions/index'>
}
declare module 'date-fns/fp/compareAsc/index.js' {
  declare module.exports: $Exports<'date-fns/fp/compareAsc/index'>
}
declare module 'date-fns/fp/compareAscWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/compareAscWithOptions/index'>
}
declare module 'date-fns/fp/compareDesc/index.js' {
  declare module.exports: $Exports<'date-fns/fp/compareDesc/index'>
}
declare module 'date-fns/fp/compareDescWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/compareDescWithOptions/index'>
}
declare module 'date-fns/fp/differenceInCalendarDays/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInCalendarDays/index'>
}
declare module 'date-fns/fp/differenceInCalendarDaysWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarDaysWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarISOWeeks/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarISOWeeks/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarISOWeeksWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarISOWeeksWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarISOYears/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarISOYears/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarISOYearsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarISOYearsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarMonths/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarMonths/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarMonthsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarMonthsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarQuarters/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarQuarters/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarQuartersWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarQuartersWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarWeeks/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarWeeks/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarWeeksWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarWeeksWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarYears/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarYears/index'
  >
}
declare module 'date-fns/fp/differenceInCalendarYearsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInCalendarYearsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInDays/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInDays/index'>
}
declare module 'date-fns/fp/differenceInDaysWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInDaysWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInHours/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInHours/index'>
}
declare module 'date-fns/fp/differenceInHoursWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInHoursWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInISOYears/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInISOYears/index'>
}
declare module 'date-fns/fp/differenceInISOYearsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInISOYearsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInMilliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInMilliseconds/index'>
}
declare module 'date-fns/fp/differenceInMillisecondsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInMillisecondsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInMinutes/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInMinutes/index'>
}
declare module 'date-fns/fp/differenceInMinutesWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInMinutesWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInMonths/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInMonths/index'>
}
declare module 'date-fns/fp/differenceInMonthsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInMonthsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInQuarters/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInQuarters/index'>
}
declare module 'date-fns/fp/differenceInQuartersWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInQuartersWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInSeconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInSeconds/index'>
}
declare module 'date-fns/fp/differenceInSecondsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInSecondsWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInWeeks/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInWeeks/index'>
}
declare module 'date-fns/fp/differenceInWeeksWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInWeeksWithOptions/index'
  >
}
declare module 'date-fns/fp/differenceInYears/index.js' {
  declare module.exports: $Exports<'date-fns/fp/differenceInYears/index'>
}
declare module 'date-fns/fp/differenceInYearsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/differenceInYearsWithOptions/index'
  >
}
declare module 'date-fns/fp/eachDayOfInterval/index.js' {
  declare module.exports: $Exports<'date-fns/fp/eachDayOfInterval/index'>
}
declare module 'date-fns/fp/eachDayOfIntervalWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/eachDayOfIntervalWithOptions/index'
  >
}
declare module 'date-fns/fp/endOfDay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfDay/index'>
}
declare module 'date-fns/fp/endOfDayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfDayWithOptions/index'>
}
declare module 'date-fns/fp/endOfHour/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfHour/index'>
}
declare module 'date-fns/fp/endOfHourWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfHourWithOptions/index'>
}
declare module 'date-fns/fp/endOfISOWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfISOWeek/index'>
}
declare module 'date-fns/fp/endOfISOWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfISOWeekWithOptions/index'>
}
declare module 'date-fns/fp/endOfISOYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfISOYear/index'>
}
declare module 'date-fns/fp/endOfISOYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfISOYearWithOptions/index'>
}
declare module 'date-fns/fp/endOfMinute/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfMinute/index'>
}
declare module 'date-fns/fp/endOfMinuteWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfMinuteWithOptions/index'>
}
declare module 'date-fns/fp/endOfMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfMonth/index'>
}
declare module 'date-fns/fp/endOfMonthWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfMonthWithOptions/index'>
}
declare module 'date-fns/fp/endOfQuarter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfQuarter/index'>
}
declare module 'date-fns/fp/endOfQuarterWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfQuarterWithOptions/index'>
}
declare module 'date-fns/fp/endOfSecond/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfSecond/index'>
}
declare module 'date-fns/fp/endOfSecondWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfSecondWithOptions/index'>
}
declare module 'date-fns/fp/endOfWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfWeek/index'>
}
declare module 'date-fns/fp/endOfWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfWeekWithOptions/index'>
}
declare module 'date-fns/fp/endOfYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfYear/index'>
}
declare module 'date-fns/fp/endOfYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/endOfYearWithOptions/index'>
}
declare module 'date-fns/fp/format/index.js' {
  declare module.exports: $Exports<'date-fns/fp/format/index'>
}
declare module 'date-fns/fp/formatDistance/index.js' {
  declare module.exports: $Exports<'date-fns/fp/formatDistance/index'>
}
declare module 'date-fns/fp/formatDistanceStrict/index.js' {
  declare module.exports: $Exports<'date-fns/fp/formatDistanceStrict/index'>
}
declare module 'date-fns/fp/formatDistanceStrictWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/formatDistanceStrictWithOptions/index'
  >
}
declare module 'date-fns/fp/formatDistanceWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/formatDistanceWithOptions/index'
  >
}
declare module 'date-fns/fp/formatRelative/index.js' {
  declare module.exports: $Exports<'date-fns/fp/formatRelative/index'>
}
declare module 'date-fns/fp/formatRelativeWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/formatRelativeWithOptions/index'
  >
}
declare module 'date-fns/fp/formatWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/formatWithOptions/index'>
}
declare module 'date-fns/fp/getDate/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDate/index'>
}
declare module 'date-fns/fp/getDateWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDateWithOptions/index'>
}
declare module 'date-fns/fp/getDay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDay/index'>
}
declare module 'date-fns/fp/getDayOfYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDayOfYear/index'>
}
declare module 'date-fns/fp/getDayOfYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDayOfYearWithOptions/index'>
}
declare module 'date-fns/fp/getDaysInMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDaysInMonth/index'>
}
declare module 'date-fns/fp/getDaysInMonthWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/getDaysInMonthWithOptions/index'
  >
}
declare module 'date-fns/fp/getDaysInYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDaysInYear/index'>
}
declare module 'date-fns/fp/getDaysInYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDaysInYearWithOptions/index'>
}
declare module 'date-fns/fp/getDayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getDayWithOptions/index'>
}
declare module 'date-fns/fp/getHours/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getHours/index'>
}
declare module 'date-fns/fp/getHoursWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getHoursWithOptions/index'>
}
declare module 'date-fns/fp/getISODay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISODay/index'>
}
declare module 'date-fns/fp/getISODayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISODayWithOptions/index'>
}
declare module 'date-fns/fp/getISOWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISOWeek/index'>
}
declare module 'date-fns/fp/getISOWeeksInYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISOWeeksInYear/index'>
}
declare module 'date-fns/fp/getISOWeeksInYearWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/getISOWeeksInYearWithOptions/index'
  >
}
declare module 'date-fns/fp/getISOWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISOWeekWithOptions/index'>
}
declare module 'date-fns/fp/getISOYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISOYear/index'>
}
declare module 'date-fns/fp/getISOYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getISOYearWithOptions/index'>
}
declare module 'date-fns/fp/getMilliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getMilliseconds/index'>
}
declare module 'date-fns/fp/getMillisecondsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/getMillisecondsWithOptions/index'
  >
}
declare module 'date-fns/fp/getMinutes/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getMinutes/index'>
}
declare module 'date-fns/fp/getMinutesWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getMinutesWithOptions/index'>
}
declare module 'date-fns/fp/getMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getMonth/index'>
}
declare module 'date-fns/fp/getMonthWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getMonthWithOptions/index'>
}
declare module 'date-fns/fp/getOverlappingDaysInIntervals/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/getOverlappingDaysInIntervals/index'
  >
}
declare module 'date-fns/fp/getOverlappingDaysInIntervalsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/getOverlappingDaysInIntervalsWithOptions/index'
  >
}
declare module 'date-fns/fp/getQuarter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getQuarter/index'>
}
declare module 'date-fns/fp/getQuarterWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getQuarterWithOptions/index'>
}
declare module 'date-fns/fp/getSeconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getSeconds/index'>
}
declare module 'date-fns/fp/getSecondsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getSecondsWithOptions/index'>
}
declare module 'date-fns/fp/getTime/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getTime/index'>
}
declare module 'date-fns/fp/getTimeWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getTimeWithOptions/index'>
}
declare module 'date-fns/fp/getYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getYear/index'>
}
declare module 'date-fns/fp/getYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/getYearWithOptions/index'>
}
declare module 'date-fns/fp/index' {
  declare module.exports: $Exports<'date-fns/fp'>
}
declare module 'date-fns/fp/index.js' {
  declare module.exports: $Exports<'date-fns/fp'>
}
declare module 'date-fns/fp/isAfter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isAfter/index'>
}
declare module 'date-fns/fp/isAfterWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isAfterWithOptions/index'>
}
declare module 'date-fns/fp/isBefore/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isBefore/index'>
}
declare module 'date-fns/fp/isBeforeWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isBeforeWithOptions/index'>
}
declare module 'date-fns/fp/isEqual/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isEqual/index'>
}
declare module 'date-fns/fp/isEqualWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isEqualWithOptions/index'>
}
declare module 'date-fns/fp/isFirstDayOfMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isFirstDayOfMonth/index'>
}
declare module 'date-fns/fp/isFirstDayOfMonthWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/isFirstDayOfMonthWithOptions/index'
  >
}
declare module 'date-fns/fp/isFriday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isFriday/index'>
}
declare module 'date-fns/fp/isFridayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isFridayWithOptions/index'>
}
declare module 'date-fns/fp/isLastDayOfMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isLastDayOfMonth/index'>
}
declare module 'date-fns/fp/isLastDayOfMonthWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/isLastDayOfMonthWithOptions/index'
  >
}
declare module 'date-fns/fp/isLeapYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isLeapYear/index'>
}
declare module 'date-fns/fp/isLeapYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isLeapYearWithOptions/index'>
}
declare module 'date-fns/fp/isMonday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isMonday/index'>
}
declare module 'date-fns/fp/isMondayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isMondayWithOptions/index'>
}
declare module 'date-fns/fp/isSameDay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameDay/index'>
}
declare module 'date-fns/fp/isSameDayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameDayWithOptions/index'>
}
declare module 'date-fns/fp/isSameHour/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameHour/index'>
}
declare module 'date-fns/fp/isSameHourWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameHourWithOptions/index'>
}
declare module 'date-fns/fp/isSameISOWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameISOWeek/index'>
}
declare module 'date-fns/fp/isSameISOWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameISOWeekWithOptions/index'>
}
declare module 'date-fns/fp/isSameISOYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameISOYear/index'>
}
declare module 'date-fns/fp/isSameISOYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameISOYearWithOptions/index'>
}
declare module 'date-fns/fp/isSameMinute/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameMinute/index'>
}
declare module 'date-fns/fp/isSameMinuteWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameMinuteWithOptions/index'>
}
declare module 'date-fns/fp/isSameMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameMonth/index'>
}
declare module 'date-fns/fp/isSameMonthWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameMonthWithOptions/index'>
}
declare module 'date-fns/fp/isSameQuarter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameQuarter/index'>
}
declare module 'date-fns/fp/isSameQuarterWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameQuarterWithOptions/index'>
}
declare module 'date-fns/fp/isSameSecond/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameSecond/index'>
}
declare module 'date-fns/fp/isSameSecondWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameSecondWithOptions/index'>
}
declare module 'date-fns/fp/isSameWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameWeek/index'>
}
declare module 'date-fns/fp/isSameWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameWeekWithOptions/index'>
}
declare module 'date-fns/fp/isSameYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameYear/index'>
}
declare module 'date-fns/fp/isSameYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSameYearWithOptions/index'>
}
declare module 'date-fns/fp/isSaturday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSaturday/index'>
}
declare module 'date-fns/fp/isSaturdayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSaturdayWithOptions/index'>
}
declare module 'date-fns/fp/isSunday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSunday/index'>
}
declare module 'date-fns/fp/isSundayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isSundayWithOptions/index'>
}
declare module 'date-fns/fp/isThursday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isThursday/index'>
}
declare module 'date-fns/fp/isThursdayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isThursdayWithOptions/index'>
}
declare module 'date-fns/fp/isTuesday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isTuesday/index'>
}
declare module 'date-fns/fp/isTuesdayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isTuesdayWithOptions/index'>
}
declare module 'date-fns/fp/isValid/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isValid/index'>
}
declare module 'date-fns/fp/isValidWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isValidWithOptions/index'>
}
declare module 'date-fns/fp/isWednesday/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isWednesday/index'>
}
declare module 'date-fns/fp/isWednesdayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isWednesdayWithOptions/index'>
}
declare module 'date-fns/fp/isWeekend/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isWeekend/index'>
}
declare module 'date-fns/fp/isWeekendWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isWeekendWithOptions/index'>
}
declare module 'date-fns/fp/isWithinInterval/index.js' {
  declare module.exports: $Exports<'date-fns/fp/isWithinInterval/index'>
}
declare module 'date-fns/fp/isWithinIntervalWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/isWithinIntervalWithOptions/index'
  >
}
declare module 'date-fns/fp/lastDayOfISOWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfISOWeek/index'>
}
declare module 'date-fns/fp/lastDayOfISOWeekWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/lastDayOfISOWeekWithOptions/index'
  >
}
declare module 'date-fns/fp/lastDayOfISOYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfISOYear/index'>
}
declare module 'date-fns/fp/lastDayOfISOYearWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/lastDayOfISOYearWithOptions/index'
  >
}
declare module 'date-fns/fp/lastDayOfMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfMonth/index'>
}
declare module 'date-fns/fp/lastDayOfMonthWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/lastDayOfMonthWithOptions/index'
  >
}
declare module 'date-fns/fp/lastDayOfQuarter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfQuarter/index'>
}
declare module 'date-fns/fp/lastDayOfQuarterWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/lastDayOfQuarterWithOptions/index'
  >
}
declare module 'date-fns/fp/lastDayOfWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfWeek/index'>
}
declare module 'date-fns/fp/lastDayOfWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfWeekWithOptions/index'>
}
declare module 'date-fns/fp/lastDayOfYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfYear/index'>
}
declare module 'date-fns/fp/lastDayOfYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/lastDayOfYearWithOptions/index'>
}
declare module 'date-fns/fp/max/index.js' {
  declare module.exports: $Exports<'date-fns/fp/max/index'>
}
declare module 'date-fns/fp/maxWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/maxWithOptions/index'>
}
declare module 'date-fns/fp/min/index.js' {
  declare module.exports: $Exports<'date-fns/fp/min/index'>
}
declare module 'date-fns/fp/minWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/minWithOptions/index'>
}
declare module 'date-fns/fp/parse/index.js' {
  declare module.exports: $Exports<'date-fns/fp/parse/index'>
}
declare module 'date-fns/fp/parseWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/parseWithOptions/index'>
}
declare module 'date-fns/fp/setDate/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setDate/index'>
}
declare module 'date-fns/fp/setDateWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setDateWithOptions/index'>
}
declare module 'date-fns/fp/setDay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setDay/index'>
}
declare module 'date-fns/fp/setDayOfYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setDayOfYear/index'>
}
declare module 'date-fns/fp/setDayOfYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setDayOfYearWithOptions/index'>
}
declare module 'date-fns/fp/setDayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setDayWithOptions/index'>
}
declare module 'date-fns/fp/setHours/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setHours/index'>
}
declare module 'date-fns/fp/setHoursWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setHoursWithOptions/index'>
}
declare module 'date-fns/fp/setISODay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setISODay/index'>
}
declare module 'date-fns/fp/setISODayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setISODayWithOptions/index'>
}
declare module 'date-fns/fp/setISOWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setISOWeek/index'>
}
declare module 'date-fns/fp/setISOWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setISOWeekWithOptions/index'>
}
declare module 'date-fns/fp/setISOYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setISOYear/index'>
}
declare module 'date-fns/fp/setISOYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setISOYearWithOptions/index'>
}
declare module 'date-fns/fp/setMilliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setMilliseconds/index'>
}
declare module 'date-fns/fp/setMillisecondsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/setMillisecondsWithOptions/index'
  >
}
declare module 'date-fns/fp/setMinutes/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setMinutes/index'>
}
declare module 'date-fns/fp/setMinutesWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setMinutesWithOptions/index'>
}
declare module 'date-fns/fp/setMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setMonth/index'>
}
declare module 'date-fns/fp/setMonthWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setMonthWithOptions/index'>
}
declare module 'date-fns/fp/setQuarter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setQuarter/index'>
}
declare module 'date-fns/fp/setQuarterWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setQuarterWithOptions/index'>
}
declare module 'date-fns/fp/setSeconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setSeconds/index'>
}
declare module 'date-fns/fp/setSecondsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setSecondsWithOptions/index'>
}
declare module 'date-fns/fp/setYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setYear/index'>
}
declare module 'date-fns/fp/setYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/setYearWithOptions/index'>
}
declare module 'date-fns/fp/startOfDay/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfDay/index'>
}
declare module 'date-fns/fp/startOfDayWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfDayWithOptions/index'>
}
declare module 'date-fns/fp/startOfHour/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfHour/index'>
}
declare module 'date-fns/fp/startOfHourWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfHourWithOptions/index'>
}
declare module 'date-fns/fp/startOfISOWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfISOWeek/index'>
}
declare module 'date-fns/fp/startOfISOWeekWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/startOfISOWeekWithOptions/index'
  >
}
declare module 'date-fns/fp/startOfISOYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfISOYear/index'>
}
declare module 'date-fns/fp/startOfISOYearWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/startOfISOYearWithOptions/index'
  >
}
declare module 'date-fns/fp/startOfMinute/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfMinute/index'>
}
declare module 'date-fns/fp/startOfMinuteWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfMinuteWithOptions/index'>
}
declare module 'date-fns/fp/startOfMonth/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfMonth/index'>
}
declare module 'date-fns/fp/startOfMonthWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfMonthWithOptions/index'>
}
declare module 'date-fns/fp/startOfQuarter/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfQuarter/index'>
}
declare module 'date-fns/fp/startOfQuarterWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/startOfQuarterWithOptions/index'
  >
}
declare module 'date-fns/fp/startOfSecond/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfSecond/index'>
}
declare module 'date-fns/fp/startOfSecondWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfSecondWithOptions/index'>
}
declare module 'date-fns/fp/startOfWeek/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfWeek/index'>
}
declare module 'date-fns/fp/startOfWeekWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfWeekWithOptions/index'>
}
declare module 'date-fns/fp/startOfYear/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfYear/index'>
}
declare module 'date-fns/fp/startOfYearWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/startOfYearWithOptions/index'>
}
declare module 'date-fns/fp/subDays/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subDays/index'>
}
declare module 'date-fns/fp/subDaysWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subDaysWithOptions/index'>
}
declare module 'date-fns/fp/subHours/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subHours/index'>
}
declare module 'date-fns/fp/subHoursWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subHoursWithOptions/index'>
}
declare module 'date-fns/fp/subISOYears/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subISOYears/index'>
}
declare module 'date-fns/fp/subISOYearsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subISOYearsWithOptions/index'>
}
declare module 'date-fns/fp/subMilliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subMilliseconds/index'>
}
declare module 'date-fns/fp/subMillisecondsWithOptions/index.js' {
  declare module.exports: $Exports<
    'date-fns/fp/subMillisecondsWithOptions/index'
  >
}
declare module 'date-fns/fp/subMinutes/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subMinutes/index'>
}
declare module 'date-fns/fp/subMinutesWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subMinutesWithOptions/index'>
}
declare module 'date-fns/fp/subMonths/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subMonths/index'>
}
declare module 'date-fns/fp/subMonthsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subMonthsWithOptions/index'>
}
declare module 'date-fns/fp/subQuarters/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subQuarters/index'>
}
declare module 'date-fns/fp/subQuartersWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subQuartersWithOptions/index'>
}
declare module 'date-fns/fp/subSeconds/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subSeconds/index'>
}
declare module 'date-fns/fp/subSecondsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subSecondsWithOptions/index'>
}
declare module 'date-fns/fp/subWeeks/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subWeeks/index'>
}
declare module 'date-fns/fp/subWeeksWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subWeeksWithOptions/index'>
}
declare module 'date-fns/fp/subYears/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subYears/index'>
}
declare module 'date-fns/fp/subYearsWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/subYearsWithOptions/index'>
}
declare module 'date-fns/fp/toDate/index.js' {
  declare module.exports: $Exports<'date-fns/fp/toDate/index'>
}
declare module 'date-fns/fp/toDateWithOptions/index.js' {
  declare module.exports: $Exports<'date-fns/fp/toDateWithOptions/index'>
}
